sonar.projectKey=Ineees24_skillhub2
sonar.organization=ineees24
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.sources=skillhub-back/app,skillhub-back/routes,skillhub-back/bootstrap,skillhub-back/config,skillhub-back/database,skillhub-front/src
sonar.tests=skillhub-back/tests

sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,**/storage/**,**/bootstrap/cache/**,skillhub-back/public/**
sonar.test.inclusions=skillhub-back/tests/**/*.php
